### PR TITLE
2023W2 minor changes

### PR DESCRIPTION
**Pull request by rtholmes**
Now that #99 has been merged (which contained the major work for WT1 and WT2), any minor remaining work for the term can be collected here.

### CODE REVIEW

**Comment by winstan** [comment]
@rtholmes - merged in CI updates from upstream.
Followed https://circleci.com/docs/migrate-scheduled-workflows-to-scheduled-pipelines/ and updated CI for ubccpsc310 as well as ubccpsc. I don't know what you'd prefer for the nightly run via ubccpsc310 - at least it can diverge from the parent now and it's much easier to run on command now.

**Comment by rtholmes** [comment]
@winstan the 310 fork of classy is already running on Circle so we're fine from the 310-end.

https://app.circleci.com/pipelines/github/ubccpsc310/classy

**Comment by winstan** [comment]
@rtholmes this is what's new (I moved it here):
https://app.circleci.com/settings/project/github/ubccpsc310/classy/triggers
The trigger for the nightly build moved from config.yml to a Circle settings page.

**Comment by winstan** [comment]
@rtholmes  Can we close this PR so I can merge it upstream? (Are you done with 310 changes for now?)
We need to do this before the summer term starts.

**Comment by rtholmes** [comment]
@winstan done (and CI is passing on main)

**Pull request merged**
