### PR TITLE
Merge/ubccpsc winter term 2

### PR DESCRIPTION
**Pull request by andrewstec**
Feature Summary: 

- New team and staff parameterization @jopika Jonathan added from 330 (BREAKING CHANGES: REQUIRES `.env` update!)
- Replaces Request with Fetch (BREAKING CHANGES: Cpsc310 may need to remove request-promise references if more of them exist in their downstream fork, as Request was removed from package.json files)
- Updated package.json files to remove RP, add Fetch, and update dependencies for security.
- Update Classlist API/Classlist upload to prefer PREF over FIRST name field.
- Updates CircleCI testing configurations (not a breaking change for 310 CircleCI though)
- Lots of updates to documentation
- Updates yarn.lock
- Adds Query String util for Fetch

### CODE REVIEW

**Comment by andrewstec** [comment]
If you guys want, we can fix some things before merging. 

ie. Disabling CircleCI nightly builds, integrate Coveralls by setting up a token.

**Comment by andrewstec** [comment]
If you have not already, please add this to your `.env` configuration.

```
## Github Team Names for the Admin and Staff list
ADMIN_TEAM_NAME=admin
STAFF_TEAM_NAME=staff
```

**Comment by rtholmes** [comment]
@andrewstec it would be great to have coveralls / circleci configured to run properly on the 310 fork, I don't think we ever configured those. Is there something you would need for us to get that setup?

**Comment by andrewstec** [comment]
Just for reference, decided what files to merge here: https://github.com/ubccpsc310/classy/pull/56.

**Comment by rtholmes** [comment]
> If you have not already, please add this to your `.env` configuration.
> 
> ```
> ## Github Team Names for the Admin and Staff list
> ADMIN_TEAM_NAME=admin
> STAFF_TEAM_NAME=staff
> ```

@andrewstec I don't know if I have write access to the 310 instance for this term; could you just add those to the current 310 `.env` so when it gets refreshed for next term it is already there?

**Comment by andrewstec** [comment]
> > If you have not already, please add this to your `.env` configuration.
> > ```
> > ## Github Team Names for the Admin and Staff list
> > ADMIN_TEAM_NAME=admin
> > STAFF_TEAM_NAME=staff
> > ```
> 
> @andrewstec I don't know if I have write access to the 310 instance for this term; could you just add those to the current 310 `.env` so when it gets refreshed for next term it is already there?

I will add those right now. Thanks for the heads-up!

**Comment by andrewstec** [comment]
> ## Github Team Names for the Admin and Staff list
> ADMIN_TEAM_NAME=admin
> STAFF_TEAM_NAME=staff

Already there. I may have done that earlier.

**Comment by andrewstec** [comment]
> @andrewstec it would be great to have coveralls / circleci configured to run properly on the 310 fork, I don't think we ever configured those. Is there something you would need for us to get that setup?

Sorry Reid. I just saw this in my email. I missed your question on Github. 

The Coveralls token is all we need at the moment to get CircleCI setup. Once it is added to the ubccpsc310/classy CircleCI environmental settings, the CircleCI runs should pass without any problem. The only part failing in the pipeline is the Coveralls upload.

**Comment by andrewstec** [comment]
> > @andrewstec it would be great to have coveralls / circleci configured to run properly on the 310 fork, I don't think we ever configured those. Is there something you would need for us to get that setup?
> 
> Sorry Reid. I just saw this in my email. I missed your question on Github.
> 
> The Coveralls token is all we need at the moment to get CircleCI setup. Once it is added to the ubccpsc310/classy CircleCI environmental settings, the CircleCI runs should pass without any problem. The only part failing in the pipeline is the Coveralls upload.
> 
> The rest is done :)

FYI, It looks like I can get permission to the Coveralls token if I have higher access permissions to the `classy` ubccpsc310 repository.

**Comment by rtholmes** [comment]
@andrewstec I don't even have access, the way registration worked it ended up that @nickbradley owns the permissions on that account. @nickbradley is there a way to send that to @andrewstec ? (they sent a password recovery to your live account the other day, but I can't do it either)

**Comment by andrewstec** [comment]
> @andrewstec I don't even have access, the way registration worked it ended up that @nickbradley owns the permissions on that account. @nickbradley is there a way to send that to @andrewstec ? (they sent a password recovery to your live account the other day, but I can't do it either)

Ah no worries! I wasn't aware of that. This is not urgent, so I can wait.

**Comment by andrewstec** [comment]
Hooray :) 

CircleCI is integrated and works: 

image

https://circleci.com/gh/ubccpsc310/classy

**Pull request merged**
